In [48]:
import pandas as pd

In [49]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [57]:
df.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01

In [59]:
1. How many records are in the dataset?
num_records = df.shape[0]

# 2. How many laptop brands are presented in the dataset?
num_brands = df['Brand'].nunique()

# 3. How many columns in the dataset have missing values?
num_missing_cols = df.isnull().sum()[df.isnull().sum() > 0].count()

# 4. What's the maximum final price of Dell notebooks in the dataset?
max_dell_price = df[df['Brand'] == 'Dell']['Final Price'].max()

# 5. Median value of Screen
# Initial median value of the Screen column
initial_median_screen = df['Screen'].median()

# Most frequent value of the Screen column
most_frequent_screen = df['Screen'].mode()[0]

# Fill missing values in the Screen column with the most frequent value
df['Screen'].fillna(most_frequent_screen, inplace=True)

# Median value of Screen after filling missing values
new_median_screen = df['Screen'].median()

# 6. Selecting all the "Innjoo" laptops and extracting columns RAM, Storage, Screen
innjoo_laptops = df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']]

# Convert selected columns to NumPy array (X)
X = innjoo_laptops.values

# Matrix-matrix multiplication of X.T and X (XTX)
XTX = X.T @ X

# Inverse of XTX
XTX_inv = np.linalg.inv(XTX)

# Create array y
y = np.array([1100, 1300, 800, 900, 1000, 1100])

# Compute w = (XTX_inv @ X.T) @ y
w = XTX_inv @ X.T @ y

# Sum of all elements in w
w_sum = np.sum(w)
print(f"Number of records: {num_records}")
print(f"Number of laptop brands: {num_brands}")
print(f"Number of columns with missing values: {num_missing_cols}")
print(f"Maximum final price of Dell notebooks: €{max_dell_price}")
print(f"Initial median screen value: {initial_median_screen}")
print(f"Most frequent screen value: {most_frequent_screen}")
print(f"Median screen value after filling missing values: {new_median_screen}")
print(f"Sum of all elements in w: {w_sum}")

Object `dataset` not found.
Number of records: 2160
Number of laptop brands: 27
Number of columns with missing values: 2
Maximum final price of Dell notebooks: €3936.0
Initial median screen value: 15.6
Most frequent screen value: 15.6
Median screen value after filling missing values: 15.6
Sum of all elements in w: 91.2998806299555

/tmp/ipykernel_33471/3053952112.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Screen'].fillna(most_frequent_screen, inplace=True)